name: delivoo
description: A new Flutter application.

version: 1.0.3+1

environment:
  sdk: ">=2.3.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  flappy_search_bar: 1.4.1
  cupertino_icons: ^0.1.2
  flutter_phoenix:
  country_code_picker: ^1.3.15
  grouped_buttons:
  mvc_pattern:
  connectivity: ^0.3.2
  google_fonts: ^1.1.0
  global_configuration: 1.5.0
  shared_preferences: 0.5.7
  image_picker: 0.6.7+11
  toast: ^0.1.5
  timeline_tile: ^1.0.0
  flutter_showcase: ^0.1.0
  cached_network_image:
  http: 0.12.1
  sqflite: ^1.2.0
  firebase_auth: 0.16.1
  razorpay_flutter: ^1.2.2
  carousel_pro: ^1.0.0
  carousel_slider: 2.3.1
  esys_flutter_share: ^1.0.2
  paytm: ^1.0.7
  firebase_messaging:
  overlay_support: ^1.0.5
  firebase_core: 0.4.5
  firebase_dynamic_links:
  flutter_spinkit: "^4.1.2"
  flutter_local_notifications: ^3.0.1
  path:
  shimmer: ^1.1.2
  path_provider: ^1.5.1
  url_launcher:




dev_dependencies:
  flutter_test:
    sdk: flutter
  intl_translation: ^0.17.9


fonts:
  - family: Raleway
    fonts:
      - asset: fonts/Raleway-LightItalic.ttf
        weight: 300

flutter:
  uses-material-design: true
  assets:
    - images/
    - images/account/
    - images/address/
    - images/custom/
    - images/footermenu/
    - images/icons/
    - images/logos/
    - images/maincategory/
    - images/veg/
    - images/veg/Sellers/
    - images/veg/Vegetables/
    - images/payment/

          